version: '2'
services:
  backend:
    build: .
    ports:
      - "8080:80"
    volumes:
      - "$PWD/src/home_budget:/go/src/home_budget"
    environment:
      - POSTGRES_HOSTNAME=postgresql
      - POSTGRES_PASSWORD=secret123secret
      - POSTGRES_USER=home_budget
      - POSTGRES_DB=home_budget
    depends_on:
      - postgresql
  postgresql:
    image: "postgres:9.6.2-alpine"
    environment:
      - POSTGRES_PASSWORD=secret123secret
      - POSTGRES_USER=home_budget
      - POSTGRES_DB=home_budget
